# Site settings
title: My I/O
email: wdicharry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog about programming, math, violin, hiking, biking and whatever else I
    feel like writing about.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wdicharry.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wdicharry

# Build settings
markdown: kramdown
